CREATE TABLE BRAND(
    ID INT PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL
);

CREATE TABLE PRODUCT(
    ID INT PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL
);

CREATE TABLE PRICES (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  BRAND_ID INT NOT NULL,
  START_DATE TIMESTAMP NOT NULL,
  END_DATE TIMESTAMP NOT NULL,
  PRICE_LIST INT NOT NULL,
  PRODUCT_ID INT NOT NULL,
  PRIORITY INT NOT NULL,
  PRICE DECIMAL(10,2) NOT NULL,
  CURR VARCHAR(10) NOT NULL,
  FOREIGN KEY (BRAND_ID) REFERENCES BRAND(ID),
  FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(ID)
);
